services:
    database:
        container_name: ${PROJECT_NAME:-ms-gateway}-db
        image: postgres:${POSTGRES_VERSION:-16.6}
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-developer}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty123}
            POSTGRES_DB: ${POSTGRES_DB:-ms-gateway-db}
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-ms-gateway-db}", "-U", "${POSTGRES_USER:-developer}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        restart: always
        volumes:
            - ms-gateway-db-data:/var/lib/postgresql/data/
        ports:
            - ${DB_PORT:-5432}:5432

volumes:
    ms-gateway-db-data: ~
