// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tjaszai/go-ms-gateway/internal/db"
	"github.com/tjaszai/go-ms-gateway/internal/http/controller"
	"github.com/tjaszai/go-ms-gateway/internal/http/middleware"
	"github.com/tjaszai/go-ms-gateway/internal/http/server"
	"github.com/tjaszai/go-ms-gateway/internal/repository"
	"github.com/tjaszai/go-ms-gateway/internal/service"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	defaultController := controller.NewDefaultController()
	databaseManager := db.NewDatabaseManager()
	gatewayController := controller.NewGatewayController(databaseManager)
	microserviceRepository := repository.NewMicroserviceRepository(databaseManager)
	validator := service.NewValidator()
	microserviceController := controller.NewMicroserviceController(microserviceRepository, validator)
	userRepository := repository.NewUserRepository(databaseManager)
	securityService := service.NewSecurityService(userRepository)
	securityController := controller.NewSecurityController(userRepository, validator, securityService)
	userController := controller.NewUserController(userRepository, validator)
	adminGuardMiddleware := middleware.NewAdminGuardMiddleware(securityService)
	authMiddleware := middleware.NewAuthMiddleware(securityService)
	serverServer := server.NewServer(defaultController, gatewayController, microserviceController, securityController, userController, adminGuardMiddleware, authMiddleware)
	return serverServer, nil
}
